name: Build and Deploy Sphinx Docs
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme myst-parser
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .

      - name: Build documentation
        run: |
          make docs
          touch _build/html/.nojekyll

      - name: Deploy to GitHub Pages
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch) && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          branch: gh-pages
          clean: true
